// <auto-generated />
using Livraria.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Livraria.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220731144048_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Livraria.API.Models.Editora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Editoras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Cascavel",
                            Nome = "Bem me quer"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "RJ",
                            Nome = "Flores balas"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "Horizonte",
                            Nome = "Produtos Ivone"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "São Paulo",
                            Nome = "Nuvem"
                        },
                        new
                        {
                            Id = 5,
                            Cidade = "Fortaleza",
                            Nome = "Luz"
                        });
                });

            modelBuilder.Entity("Livraria.API.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .HasColumnType("TEXT");

                    b.Property<int>("EditoraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lancamento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalAlugado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EditoraId");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Juliano Santos",
                            EditoraId = 1,
                            Lancamento = 23072001,
                            Nome = "Flor de Verão",
                            Quantidade = 10,
                            TotalAlugado = 23
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Alex Santos",
                            EditoraId = 3,
                            Lancamento = 8072001,
                            Nome = "Flor",
                            Quantidade = 68,
                            TotalAlugado = 90
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Raquel Lovewood",
                            EditoraId = 5,
                            Lancamento = 23082001,
                            Nome = "Oi vida",
                            Quantidade = 10,
                            TotalAlugado = 36
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Ana Luana",
                            EditoraId = 2,
                            Lancamento = 23072004,
                            Nome = "Feliz mas não",
                            Quantidade = 3,
                            TotalAlugado = 23
                        },
                        new
                        {
                            Id = 5,
                            Autor = "Lara Alencar",
                            EditoraId = 4,
                            Lancamento = 13072001,
                            Nome = "Doce tristeza",
                            Quantidade = 53,
                            TotalAlugado = 46
                        });
                });

            modelBuilder.Entity("Livraria.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Cascavel",
                            Email = "Artur@gmail.com",
                            Endereco = "Rua A",
                            Nome = "Artur"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Caucaia",
                            Email = "Ana@gmail.com",
                            Endereco = "Rua T",
                            Nome = "Ana"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "São Paulo",
                            Email = "Vilma@gmail.com",
                            Endereco = "Rua K",
                            Nome = "Vilma"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Fortaleza",
                            Email = "Vitor@gmail.com",
                            Endereco = "Rua E",
                            Nome = "Vitor"
                        });
                });

            modelBuilder.Entity("Livraria.API.Models.Livro", b =>
                {
                    b.HasOne("Livraria.API.Models.Editora", "Editora")
                        .WithMany()
                        .HasForeignKey("EditoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
