// <auto-generated />
using Livraria.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Livraria.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220729184403_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Livraria.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Cascavel",
                            Email = "Artur@gmail.com",
                            Endereco = "Rua A",
                            Nome = "Artur"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Caucaia",
                            Email = "Ana@gmail.com",
                            Endereco = "Rua T",
                            Nome = "Ana"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "São Paulo",
                            Email = "Vilma@gmail.com",
                            Endereco = "Rua K",
                            Nome = "Vilma"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Fortaleza",
                            Email = "Vitor@gmail.com",
                            Endereco = "Rua E",
                            Nome = "Vitor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
